[project]
name = "pygbase-engine"
version = "0.0.2"
description = "A simple engine based on pygame-ce"
readme = "README.md"
authors = [{ name = "Tiger Zhang", email = "yu266426@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["pygame", "pygame-ce", "game", "game engine"]
dependencies = [
    "pygame-ce>=2.5.7",
]
requires-python = ">=3.14"

[project.urls]
Homepage = "https://github.com/Yu266426/pygbase"

[project.scripts]
examples = "examples:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pygbase"
# module-root = "src"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.ruff]
fix = true
line-length = 120

[tool.ruff.format]
indent-style = "tab"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["RUF012", "SIM117", "SIM102"]
